# ----
# Site

title: The Sinnarasa Foundation
url: https://sinnarasa.com
baseurl:
google_analytics_key:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Jekyll template with example content for a not-for-profit organisation.
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Cause Template
  links:
    - https://github.com/CloudCannon/cause-jekyll-template

# -----
# Build

timezone: Etc/UTC

collections:
  staff_members:
    _icon: account_circle
    _hide_content: true
    _options:
      image:
        width: 250
        height: 250

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1880
          height: 1880
          uploads_dir: "/images/posts/"
  -
    scope:
      path: ""
    values:
      layout: "default"

donation_embed: '<div><p>To make a donation to the Anton Sinnarasa Philip's Trust, and honor his memory by helping us continue his projects, please send an eTransfer to <a href="mailto:trust@sinnarasa.com"><strong>trust@sinnarasa.com</strong></a>.</p><p> If you are outside Canada, you can visit <a href="paypal.me/sinnarasatrust">paypal.me/sinnarasatrust</a> instetad.</p></div>'
newsletter_action: "https://sinnarasa.us17.list-manage.com/subscribe/post?u=74cab5254891f5d33fa90ec10&amp;id=7aa1c23a5d&amp;f_id=00336ae0f0"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

_options:
  header_background_image:
    width: 1880
    height: 1880
  newsletter_background_image:
    width: 1880
    height: 1880
